"""
languages.py – Sprachdefinitionen für STFC Calc

Enthält alle Texte in Deutsch und Englisch
"""

LANGS = {
    "de": {
        "title": "⬡  STFC CALC  ⬡",
        "tab_calc": "  ◆ Berechnung  ",
        "tab_saves": "  ◈ Verlauf      ",
        "status_ready": "Werte eingeben → Ergebnis erscheint automatisch.",
        "power_title": "SCHIFFSSTÄRKE",
        "power_info": "Deine gesamte Flottenstärke (alle teilnehmenden Schiffe summiert).",
        "power_label": "Stärke eingeben  (z. B. 2000000 oder 2.000.000)",
        "armada_title": "ARMADA-TYP",
        "armada_info": "Welche Armada wollt ihr angreifen?",
        "armada_label": "Armada-Typ auswählen:",
        "armada_tooltip": "Wähle den Schwierigkeitsgrad der Armada",
        "crew_title": "CREW-QUALITÄT",
        "crew_info": "Welche Offiziere sind auf deinem Schiff?",
        "crew_label": "Crew-Qualität auswählen:",
        "crew_tooltip": "Wähle die Qualität deiner Crew-Offiziere",
        "res_title": "FORSCHUNGSSTAND",
        "res_info": "Armada-Forschung im Baum 'Station' & 'Kampf'",
        "res_label": "Forschungsstand auswählen:",
        "res_tooltip": "Wähle deinen Forschungsstand in Armada-Bäumen",
        "result_title": "ERGEBNIS",
        "result_label": "Max. besiegbare Armada-Stärke:",
        "result_start": "Stärke eingeben um zu beginnen.",
        "btn_calc": "💾  SPEICHERN",
        "btn_clear": "✖  LEEREN",
        "tips_title": "TIPPS",
        "tips_start": "Stärke eingeben für Tipps.",
        "tips_crew": "💡 Optimale Crew gibt +20% mehr Kapazität.",
        "tips_research": "🔬 Armada-Forschung gibt +10% Bonus.",
        "tips_epic": "⚠️ Epic BRAUCHT optimale Crew!",
        "tips_optimal": "✅ Optimale Einstellungen!",
        "warn_title": "⚠  HINWEISE",
        "warn_text": "• 100-Runden-Limit: Nicht gewonnen\n  = Niederlage.\n\n• One-Shot: Schiff zu klein = sofort\n  vernichtet, kein Rechner hilft.\n\n• Solo: Kein Allianz-Schadensbonus.",
        "formula_invalid": "Ungültige Eingabe.\nNur Zahlen, z. B. 2000000",
        "saves_title": "GESPEICHERTE BERECHNUNGEN",
        "saves_info": "Alle gespeicherten Kalkulationen – exportierbar als CSV.",
        "saves_cols": ["Datum", "Stärke", "Armada", "Crew", "Forschung", "Max. Armada"],
        "btn_export": "📤  CSV EXPORTIEREN",
        "btn_delete": "✖  AUSWAHL LÖSCHEN",
        "btn_clear_all": "🗑  ALLES LÖSCHEN",
        "msg_hint": "Hinweis",
        "msg_enter_power": "Zuerst eine gültige Stärke eingeben!",
        "msg_saved": "Gespeichert",
        "msg_saved_text": "Ergebnis gespeichert!\nMax. Armada-Stärke: {result}",
        "msg_empty": "Leer",
        "msg_no_entries": "Keine Einträge vorhanden.",
        "msg_exported": "Exportiert",
        "msg_exported_text": "Gespeichert:\n{path}",
        "msg_clear_all": "Löschen?",
        "msg_clear_all_text": "Wirklich alle Einträge löschen?",
        "msg_cleared": "Felder geleert.",
        "status_saved": "✔  Gespeichert: {result}",
        "status_result": "✔  Max. Armada-Stärke:  {result}",
    },
    "en": {
        "title": "⬡  STFC CALC  ⬡",
        "tab_calc": "  ◆ Calculation  ",
        "tab_saves": "  ◈ History      ",
        "status_ready": "Enter values → Result appears automatically.",
        "power_title": "FLEET POWER",
        "power_info": "Your total fleet power (sum of all participating ships).",
        "power_label": "Enter power  (e.g. 2000000 or 2,000,000)",
        "armada_title": "ARMADA TYPE",
        "armada_info": "Which armada do you want to attack?",
        "armada_label": "Select armada type:",
        "armada_tooltip": "Choose the armada difficulty level",
        "crew_title": "CREW QUALITY",
        "crew_info": "Which officers are on your ship?",
        "crew_label": "Select crew quality:",
        "crew_tooltip": "Choose the quality of your crew officers",
        "res_title": "RESEARCH LEVEL",
        "res_info": "Armada research in 'Station' & 'Combat' trees",
        "res_label": "Select research level:",
        "res_tooltip": "Choose your research level in armada trees",
        "result_title": "RESULT",
        "result_label": "Max. armada power you can defeat:",
        "result_start": "Enter power to get started.",
        "btn_calc": "💾  SAVE",
        "btn_clear": "✖  CLEAR",
        "tips_title": "TIPS",
        "tips_start": "Enter power for tips.",
        "tips_crew": "💡 Optimal crew gives +20% more capacity.",
        "tips_research": "🔬 Armada research gives +10% bonus.",
        "tips_epic": "⚠️ Epic REQUIRES optimal crew!",
        "tips_optimal": "✅ Optimal settings!",
        "warn_title": "⚠  NOTES",
        "warn_text": "• 100-Round Limit: Not won = Defeat.\n\n• One-Shot: Ship too small = instantly\n  destroyed, no calculator helps.\n\n• Solo: No alliance damage bonus.",
        "formula_invalid": "Invalid input.\nNumbers only, e.g. 2000000",
        "saves_title": "SAVED CALCULATIONS",
        "saves_info": "All saved calculations – exportable as CSV.",
        "saves_cols": ["Date", "Power", "Armada", "Crew", "Research", "Max Armada"],
        "btn_export": "📤  EXPORT CSV",
        "btn_delete": "✖  DELETE SELECTION",
        "btn_clear_all": "🗑  DELETE ALL",
        "msg_hint": "Note",
        "msg_enter_power": "First enter a valid power value!",
        "msg_saved": "Saved",
        "msg_saved_text": "Result saved!\nMax. Armada Power: {result}",
        "msg_empty": "Empty",
        "msg_no_entries": "No entries available.",
        "msg_exported": "Exported",
        "msg_exported_text": "Saved:\n{path}",
        "msg_clear_all": "Delete?",
        "msg_clear_all_text": "Really delete all entries?",
        "msg_cleared": "Fields cleared.",
        "status_saved": "✔  Saved: {result}",
        "status_result": "✔  Max. Armada Power:  {result}",
    },
}
